### ISSUE TITLE
Handling of duplicates in a multi-account setup

### ISSUE THREAD

**Issue by xaltsc** [michaeladler/notmuch-mailmover#129]
Hey,
I'm having an issue trying to use `notmuch-mailmover` with my multi-account setup.
Basically, I have several mailboxes under a single folder and a single `notmuch` profile. On some of these adresses, I'm subscribed to the same mailing lists. Because of how notmuch is conceived, these report as duplicates.

Now, what I want to do with `notmuch-mailmover` is to act only on the folder representing a mailbox. Because of `notmuch`, predicates like `path:mailbox1/**` don't disambiguate between mailboxes. Such disambiguisation would have to be done later, when `notmuch-mailmover` retrieves the filepaths.

I think my setup is fairly common (given #98, #116) and oughts to be considered.

**Comment by michaeladler** [comment]
Hi @xaltsc,

could you sketch your folder structure please (ideally, using something like `tree`)? It sounds like you're having a single`Inbox` folder where you just throw the mails of all accounts into, which seems a bit odd. In all other cases I don't see why you wouldn't be able to add a `folder:` clause to your queries.

**Comment by xaltsc** [comment]
No, I have a folder with immediate subfolders being mail accounts as in the following:

```
~/mail
├── account1 
│   ├── Archive
│   ├── Drafts
│   ├── INBOX
│   ├── Junk
│   ├── Sent
│   └── Trash
├── account2
│   ├── INBOX
│   ├── SPAM
│   ├── Sent
│   └── Trash
…
```

The `folder:` clause doesn't work because, as explained in `notmuch-search-terms(7)`, "folder:  will  find  a message if any copy of that message is in the specific folder.". Since I receive the same message in `account1/INBOX` and `account2/INBOX`, `notmuch` considers them as duplicates and I cannot disambiguate them.

I'm drafting up a PR at the moment for this. Do you have any specific requirements considering contributions ?

**Comment by michaeladler** [comment]
Nothing out of the ordinary; just be sure to comply with the Apache 2.0 license terms, which shouldn't be hard :)
