### ISSUE TITLE
`notmuch-mailmover` is not idempotent

### ISSUE THREAD

**Issue by xaltsc** [michaeladler/notmuch-mailmover#131]
Say you have this mail structure:
```
.
├── left
│   └── msg1
└── right
    └── msg2
```

And rules:
```lua
{
query =  "folder:left"
folder = "right",
},
{
query = "folder:right",
folder = "left"
}
```

Then `notmuch-mailmover` will exchange the location of each message on each invocation.

**Comment by xaltsc** [comment]
I don't know if this can happen in practice (or if it's not the end user's fault). I noticed this when fixing 
https://github.com/michaeladler/notmuch-mailmover/pull/130/commits/6691153131c7ea5a2dae438eeee447ad4e08fbe6

IMO, queries should be based on tags, paths and folder are to proscribe as they lead to this.

**Comment by michaeladler** [comment]
Yes, that's true, and it seems unlikely that we can prevent this issue entirely. Adding date clauses to the queries may even make the problem worse, as even running `notmuch-mailmover` twice may still not catch all cases. The only scenario we can reliably detect is when a message is moved multiple times during a single invocation of `notmuch-mailmover`. Should we add a note to the documentation to highlight this limitation, or do you have an alternative approach in mind to address this issue?

**Comment by xaltsc** [comment]
I don't have an alternative approach sadly, when I opened the issue, I
thought it was due to the queries with `NOT folder:{}` in the engine
(but I was the one who introduced the bug).

However I do think that it would be good to warn in the documentation,
and encourage people to write only tag-based queries.

If there are only `tag:`, `folder:` and `path:` clauses in a
queries, I have an approach in mind (that I also had for `afew` a few
years back), but it would require constructing a rewriting system,
checking that it is confluent, and compute the terminal states. I have
no idea how to do that in either Python or Rust...

**Comment by michaeladler** [comment]
> but it would require constructing a rewriting system,
> checking that it is confluent, and compute the terminal states. I have
> no idea how to do that in either Python or Rust...

Sounds error-prone... in the spirit of KISS, I’d suggest enhancing the documentation accordingly. Would you like to submit a merge request?
