### ISSUE TITLE
Update config.yml and readme

### ISSUE THREAD

**Issue by archer-65** [michaeladler/notmuch-mailmover#9]
First of all, great job!
The afew plugin is good, but notmuch-mailmover is easier. Killer feature: there is no need to specify the folder you need to move from (did I get it right?).

Anyway, the title is self-explanatory 😁

**Comment by michaeladler** [comment]
Thanks for the hint, I have updated the README.

Yes exactly, this was also my main motivation for writing this tool :) As a side effect, it's also more efficient because you don't need an extra query for every folder you have. I'm glad you find it useful, too! If you encounter any other issues, please let me know.

Fixed via ceefb11417ebe7200ef8d53c803443e00302c904

**Comment by archer-65** [comment]
I was thinking about an overlay for Nix, introducing something like:
```nix
programs.mailmover = {
  enable = true;
  package = pkgs.notmuch-mailmover;
  maildir = "...";
  ...
  rules = [
    {
      folder = "...";
      query = "...";
     }
     ...
  ];
  extraConfig = ''
    ...
  '';
};
```

I will open a pull request for this, If I can.

**Comment by michaeladler** [comment]
It probably makes sense to integrate/couple this with home-manager since it already provides `programs.notmuch.hooks.preNew`.  Also, in modules/accounts/email.nix, there is `absPath` which is needed to set the `maildir` variable in the config.

**Comment by archer-65** [comment]
> It probably makes sense to integrate/couple this with home-manager since it already provides `programs.notmuch.hooks.preNew`.  Also, in modules/accounts/email.nix, there is `absPath` which is needed to set the `maildir` variable in the config. 

If you want, I can work on the module `email.nix`. Let me know.

**Comment by archer-65** [comment]
> Sure, feel free :) I don't know how familiar you are with it, but I guess you could take some inspiration from [homeage](https://github.com/jordanisaacs/homeage).
> 
> EDIT: Sure I wouldn't mind having this in nixpkgs. For that, I should create a git tag first though.

Don't worry, I'm familiar with both of them. I will open a pull request for nixpkgs when you set a tag.

**Comment by michaeladler** [comment]
I've pushed a tag now
